server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql://39.102.33.168:3306/social?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: root
    password: 618916hhxx@Dwl
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.pm.social.domain

logging:
  level:
    com:
      pm:
        social:
          mapper: debug
